### ISSUE TITLE
Priorities list

### ISSUE THREAD

**Issue by omarjamil** [m2lines/CAM-ML#52]
The following priorities list was agreed with Paul O'Gorman in October '24.

- [x] Precipitation passed to coupler. Close by #35 
- [x] Moist to dry mixing ratios tendencies test and working. Closed by #20 
- [ ] Moist to dry number concentration tendencies tested and working. Number concentration in #39. Waiting on resolving questions around energy checker (#34)
- [ ] Energy conservation checked. Being addressed by #34.
- [x] Timing estimated compared to ZM scheme. Closed by #49.
- [x] Aquaplanet rerun with current version (after issues with mixing ratios/number concentration tendencies fixed) and check if striped bands present and/or due to aspect of implementation. Banding removed. Completed by #50
